print("rama2")
print("cambio en rama2 despues del stash")
print("cambio en rama main tras hacer un merge con la rama_2")
print("cambio en rama 2 test")
print("NUEVO CAMBIO EN MAIN, AHORA PUEDO BORRAR RAMA_2 PORQUE YA HA TERMINADO LA TAREA QUE TENÍA LA RAMA_2")